num1 = int(input("Enter the first digit "))
num2 = int(input("Enter the second digit "))
print("Performing arithmatic operations")
addition = (num1+num2)
subtraction = (num1-num2)
multiplication = (num1*num2)
division = (num1/num2)
remainder = (num1%num2)
print("The addition of the two numbers is",addition)
print("The subtraction of the two numbers is",subtraction)
print("The multiplication of the two numbers is",multiplication)
print("The division of the two numbers is",division)
print("Also the remainder after dividing the two numbers is",remainder)
